# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0758b2a30c2ee7cef3daca4d870e42e9a301acff07321ca42b409115598856aed5eae02d97938a52ae59764c4c21f2b6618f95e911788123e944a7d22f879c2

test:
  secret_key_base: 93c442c9fda26bae21c44af04223031fca6fb8c78c0f65c650fafd070181fbfb3378989f0d9ec0579ed14650b9897c20d4a48afc8c5aae364d822d0e387e744e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
